<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Funcionario extends Model
{
    protected $fillable = [
        'id',
        'Nome',
        'Matricula',
        'Cpf',
        'Rg',
        'Telefone-p',
        'Data',
        'Naturalidade',
        'sexo',
        'estado',
        'Email',
        'escola',
        'profi',
        'Crm',
        'Especialidade',
        'TIPO_PERMISAO',
        'Cep',
        'Uf',
        'cidade',
        'Endereco',
        'Bairro',
        'Numero',
        'Complemento',
        'Parente',
        'Parentent-tele',
        'Parente-1',
        'Parentent-tele-1',
        'cor',
        'Peso',
        'Altura',
        'rh',
        'tipo',
        'radioH',
        'Chere',
        'radioD',
        'CDiab',
        'radioHI',
        'Chiper',
        'radioT',
        'Cclini',
        'radioC',
        'Cdoen',
        'radioN',
        'Cneopla',
        'radioFA',
        'Cfarma',
        'radioDRO',
        'Cuso',
        'radioAL',
        'Calerg',
        'radioET',
        'Cetili',
        'radioVA',
        'Cvacina',
        'radioCI',
        'Ccirur',
        'radioTRA',
        'Cporta',
        'radioMAR',
        'Cmarca',
        'radioEP',
        'Ceplis'];
}
